name: Screenshot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to release"
        required: true
        default: "main"

jobs:
  build-and-test:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-11"   # For Apple Silicon (ARM64)
            architecture: "arm64"  # Apple Silicon
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"  # For Intel (x86_64)
            architecture: "x86_64"   # Intel
            args: "--target x86_64-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      # Add the steps for building and testing here, using `args` and architecture info if needed.

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> "$HOME/.zprofile"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> "$HOME/.bash_profile"
          eval "$(/opt/homebrew/bin/brew shellenv)"
          brew update

      - name: Tap the Homebrew repository
        run: |
          brew tap nomandhoni-cs/blinkeye && brew install --cask blinkeye

      - name: Install Blink Eye Cask
        run: |
          brew install --cask blinkeye
          screencapture -x /tmp/screenshot_install.png  # Screenshot during installation process

      - name: Verify Installation
        run: |
          if [ -d "/Applications/Blink Eye.app" ]; then
            echo "Blink Eye installed successfully."
          else
            echo "Blink Eye installation failed!" && exit 1
          fi
          screencapture -x /tmp/screenshot_verify_install.png  # Screenshot after verification

      - name: Launch Blink Eye App 5 Times with Delay
        run: |
          for i in {1..5}; do
            open "/Applications/Blink Eye.app"
            sleep 5  # Wait for the app UI to render
            screencapture -x /tmp/screenshot_launch_$i.png  # Take screenshot after wait
          done

      - name: Test App Architecture
        run: |
          if [ ! -f "/Applications/Blink Eye.app/Contents/MacOS/Blink-Eye" ]; then
            echo "Blink Eye binary not found!" && exit 1
          fi
          ARCH=$(file "/Applications/Blink Eye.app/Contents/MacOS/Blink-Eye" | awk '{print $NF}')
          echo "Detected architecture: $ARCH"
          if [ "$ARCH" != "${{ matrix.architecture }}" ]; then
            echo "Architecture test failed! Detected: $ARCH, Expected: ${{ matrix.architecture }}" && exit 1
          else
            echo "Architecture test passed! Detected: $ARCH matches ${{ matrix.architecture }}"
          fi
          screencapture -x /tmp/screenshot_architecture.png  # Screenshot during architecture check

      - name: Uninstall Blink Eye Cask
        run: |
          brew uninstall --cask blinkeye
          screencapture -x /tmp/screenshot_uninstall.png  # Screenshot during uninstallation

      - name: Verify Uninstallation
        run: |
          if [ ! -d "/Applications/Blink Eye.app" ]; then
            echo "Blink Eye uninstalled successfully."
          else
            echo "Blink Eye uninstallation failed!" && exit 1
          fi
          screencapture -x /tmp/screenshot_verify_uninstall.png  # Screenshot after uninstallation

      - name: Upload All Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: BlinkEyeScreenshots
          path: /tmp/screenshot_*.png
          retention-days: 7

