name: Update Blink Eye Cask

on:
  schedule:
    # Runs 4 times a day
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch: # Allows manual execution

jobs:
  update-cask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Latest JSON
        id: fetch-latest
        run: |
          curl -s https://github.com/nomandhoni-cs/blink-eye/releases/latest/download/latest.json -o latest.json
          echo "Fetched latest.json:"
          cat latest.json

          VERSION=$(jq -r '.version' latest.json)
          URL_ARM=$(jq -r '.platforms["darwin-aarch64"].url' latest.json)
          URL_INTEL=$(jq -r '.platforms["darwin-x86_64"].url' latest.json)

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "URL_ARM=$URL_ARM" >> $GITHUB_ENV
          echo "URL_INTEL=$URL_INTEL" >> $GITHUB_ENV

      - name: Calculate SHA256 Checksums
        id: sha256
        run: |
          curl -L -o BlinkEye_aarch64.tar.gz "$URL_ARM"
          curl -L -o BlinkEye_x64.tar.gz "$URL_INTEL"

          SHA256_ARM=$(sha256sum BlinkEye_aarch64.tar.gz | awk '{print $1}')
          SHA256_INTEL=$(sha256sum BlinkEye_x64.tar.gz | awk '{print $1}')

          echo "SHA256_ARM=$SHA256_ARM" >> $GITHUB_ENV
          echo "SHA256_INTEL=$SHA256_INTEL" >> $GITHUB_ENV

      - name: Update Cask File
        run: |
          sed -i "s/^  version \".*\"/  version \"$VERSION\"/" Casks/blinkeye.rb
          sed -i "s/^  sha256 arm:   \".*\"/  sha256 arm:   \"$SHA256_ARM\"/" Casks/blinkeye.rb
          sed -i "s/^         intel: \".*\"/         intel: \"$SHA256_INTEL\"/" Casks/blinkeye.rb
          sed -i "s|^  url .*|  url \"https://github.com/nomandhoni-cs/blink-eye/releases/download/v#{version}/Blink.Eye_#{arch}.app.tar.gz\",|" Casks/blinkeye.rb

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add Casks/blinkeye.rb
          git commit -m "Update Blink Eye Cask to v$VERSION"
          git push origin main
